/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica11;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Shape;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.awt.image.ConvolveOp;
import java.awt.image.LookupOp;
import java.awt.image.LookupTable;
import java.awt.image.RescaleOp;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import sm.image.KernelProducer;

/**
 *
 * @author Óscar
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    //Guardo la última ventana interna creada
    private VentanaInterna vi;
    private int numVentanas;
    private Shape s;

    public VentanaPrincipal() {
        initComponents();
        numVentanas = 0;
        vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        vi.setTitle("Lienzo " + ++numVentanas);
        botonLapiz.setSelected(true);
        panelColor.setVisible(true);
        panelImagen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BotonesMenu = new javax.swing.ButtonGroup();
        GrupoColores = new javax.swing.ButtonGroup();
        grupoPaletas = new javax.swing.ButtonGroup();
        paletaOpciones = new javax.swing.JPanel();
        BotonesFiguras = new javax.swing.JToolBar();
        botonLapiz = new javax.swing.JToggleButton();
        botonLinea = new javax.swing.JToggleButton();
        botonRectangulo = new javax.swing.JToggleButton();
        botonOvalo = new javax.swing.JToggleButton();
        botonesPaletas = new javax.swing.JPanel();
        botonPaletaColor = new javax.swing.JRadioButton();
        botonPaletaImagen = new javax.swing.JRadioButton();
        cuerpo = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        pie = new javax.swing.JPanel();
        paneles = new javax.swing.JPanel();
        panelImagen = new javax.swing.JPanel();
        contenedorBrillo = new javax.swing.JPanel();
        sliderBrillo = new javax.swing.JSlider();
        contenedorEfecto = new javax.swing.JPanel();
        listaEfectos = new javax.swing.JComboBox();
        contenedorContraste = new javax.swing.JPanel();
        botonContraste = new javax.swing.JButton();
        botonIluminar = new javax.swing.JButton();
        botonOscurecer = new javax.swing.JButton();
        contenedorRotacion = new javax.swing.JPanel();
        sliderRotacion = new javax.swing.JSlider();
        botonRotacion90 = new javax.swing.JButton();
        botonRotacion180 = new javax.swing.JButton();
        botonRotacion270 = new javax.swing.JButton();
        contenedorEscala = new javax.swing.JPanel();
        botonAumentar = new javax.swing.JButton();
        botonDisminuir = new javax.swing.JButton();
        panelColor = new javax.swing.JPanel();
        contenedorColores = new javax.swing.JPanel();
        panelColores = new javax.swing.JPanel();
        botonColorRojo = new javax.swing.JButton();
        botonColorNegro = new javax.swing.JButton();
        botonColorAzul = new javax.swing.JButton();
        botonColorBlanco = new javax.swing.JButton();
        botonColorVerde = new javax.swing.JButton();
        botonColorAmarillo = new javax.swing.JButton();
        contenedorGrosor = new javax.swing.JPanel();
        panelGrosor = new javax.swing.JPanel();
        grosor = new javax.swing.JSpinner();
        contenedorEditarRelleno = new javax.swing.JPanel();
        panelRelleno = new javax.swing.JPanel();
        checkboxRelleno = new javax.swing.JCheckBox();
        checkboxEditar = new javax.swing.JCheckBox();
        panelLabelFigura = new javax.swing.JPanel();
        labelFigura = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        edicion = new javax.swing.JMenu();
        verBarraEstado = new javax.swing.JCheckBoxMenuItem();
        imagen = new javax.swing.JMenu();
        menuRescaleOp = new javax.swing.JMenuItem();
        menuConvolveOp = new javax.swing.JMenuItem();
        umbralizacion = new javax.swing.JMenuItem();
        restar = new javax.swing.JMenuItem();
        multiplicar = new javax.swing.JMenuItem();
        sobelMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paletaOpciones.setLayout(new javax.swing.BoxLayout(paletaOpciones, javax.swing.BoxLayout.LINE_AXIS));

        BotonesFiguras.setRollover(true);
        BotonesFiguras.setPreferredSize(new java.awt.Dimension(273, 50));

        BotonesMenu.add(botonLapiz);
        botonLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Lapiz.gif"))); // NOI18N
        botonLapiz.setFocusable(false);
        botonLapiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLapiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonLapiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLapizMouseClicked(evt);
            }
        });
        BotonesFiguras.add(botonLapiz);

        BotonesMenu.add(botonLinea);
        botonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Linea.gif"))); // NOI18N
        botonLinea.setFocusable(false);
        botonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonLinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLineaMouseClicked(evt);
            }
        });
        BotonesFiguras.add(botonLinea);

        BotonesMenu.add(botonRectangulo);
        botonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Rectangulo.gif"))); // NOI18N
        botonRectangulo.setFocusable(false);
        botonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRectanguloMouseClicked(evt);
            }
        });
        BotonesFiguras.add(botonRectangulo);

        BotonesMenu.add(botonOvalo);
        botonOvalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ovalo.gif"))); // NOI18N
        botonOvalo.setFocusable(false);
        botonOvalo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonOvalo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonOvalo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonOvaloMouseClicked(evt);
            }
        });
        BotonesFiguras.add(botonOvalo);

        botonesPaletas.setAlignmentX(0.0F);
        botonesPaletas.setAlignmentY(0.0F);
        botonesPaletas.setMaximumSize(new java.awt.Dimension(150, 45));
        botonesPaletas.setPreferredSize(new java.awt.Dimension(125, 45));
        botonesPaletas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));

        grupoPaletas.add(botonPaletaColor);
        botonPaletaColor.setSelected(true);
        botonPaletaColor.setText("Color");
        botonPaletaColor.setFocusable(false);
        botonPaletaColor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonPaletaColor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonPaletaColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonPaletaColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPaletaColorActionPerformed(evt);
            }
        });
        botonesPaletas.add(botonPaletaColor);

        grupoPaletas.add(botonPaletaImagen);
        botonPaletaImagen.setText("Imagen");
        botonPaletaImagen.setFocusable(false);
        botonPaletaImagen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonPaletaImagen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonPaletaImagen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonPaletaImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPaletaImagenActionPerformed(evt);
            }
        });
        botonesPaletas.add(botonPaletaImagen);

        BotonesFiguras.add(botonesPaletas);

        paletaOpciones.add(BotonesFiguras);

        getContentPane().add(paletaOpciones, java.awt.BorderLayout.PAGE_START);

        cuerpo.setPreferredSize(new java.awt.Dimension(772, 400));
        cuerpo.setLayout(new java.awt.BorderLayout());
        cuerpo.add(escritorio, java.awt.BorderLayout.CENTER);

        getContentPane().add(cuerpo, java.awt.BorderLayout.CENTER);

        pie.setLayout(new java.awt.BorderLayout());

        paneles.setLayout(new javax.swing.BoxLayout(paneles, javax.swing.BoxLayout.Y_AXIS));

        panelImagen.setNextFocusableComponent(botonPaletaImagen);
        panelImagen.setPreferredSize(new java.awt.Dimension(831, 100));
        panelImagen.setLayout(new javax.swing.BoxLayout(panelImagen, javax.swing.BoxLayout.LINE_AXIS));

        contenedorBrillo.setBorder(javax.swing.BorderFactory.createTitledBorder("Brillo"));
        contenedorBrillo.setMaximumSize(new java.awt.Dimension(200, 90));
        contenedorBrillo.setMinimumSize(new java.awt.Dimension(95, 90));
        contenedorBrillo.setLayout(new java.awt.GridBagLayout());

        sliderBrillo.setMaximum(200);
        sliderBrillo.setMinimum(-200);
        sliderBrillo.setPaintLabels(true);
        sliderBrillo.setValue(0);
        sliderBrillo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderBrilloStateChanged(evt);
            }
        });
        sliderBrillo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sliderBrilloFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 200;
        gridBagConstraints.gridy = 50;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        contenedorBrillo.add(sliderBrillo, gridBagConstraints);

        panelImagen.add(contenedorBrillo);

        contenedorEfecto.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));
        contenedorEfecto.setToolTipText("");
        contenedorEfecto.setMaximumSize(new java.awt.Dimension(400, 90));
        contenedorEfecto.setMinimumSize(new java.awt.Dimension(95, 90));
        contenedorEfecto.setLayout(new java.awt.GridBagLayout());

        listaEfectos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Emborronamiento media", "Emborronamiento binomial", "Enfoque", "Relieve", "Dectector de fronteras laplaciano" }));
        listaEfectos.setMaximumSize(new java.awt.Dimension(170, 50));
        listaEfectos.setMinimumSize(new java.awt.Dimension(170, 30));
        listaEfectos.setPreferredSize(null);
        listaEfectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaEfectosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorEfecto.add(listaEfectos, gridBagConstraints);

        panelImagen.add(contenedorEfecto);

        contenedorContraste.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraste"));
        contenedorContraste.setToolTipText("");
        contenedorContraste.setMaximumSize(new java.awt.Dimension(200, 90));
        contenedorContraste.setLayout(new java.awt.GridBagLayout());

        botonContraste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contraste.png"))); // NOI18N
        botonContraste.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonContraste.setDisabledIcon(null);
        botonContraste.setMaximumSize(new java.awt.Dimension(50, 35));
        botonContraste.setMinimumSize(new java.awt.Dimension(50, 35));
        botonContraste.setPreferredSize(new java.awt.Dimension(50, 35));
        botonContraste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContrasteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        contenedorContraste.add(botonContraste, gridBagConstraints);

        botonIluminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iluminar.png"))); // NOI18N
        botonIluminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonIluminar.setDisabledIcon(null);
        botonIluminar.setMaximumSize(new java.awt.Dimension(50, 35));
        botonIluminar.setMinimumSize(new java.awt.Dimension(50, 35));
        botonIluminar.setPreferredSize(new java.awt.Dimension(50, 35));
        botonIluminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIluminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        contenedorContraste.add(botonIluminar, gridBagConstraints);

        botonOscurecer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/oscurecer.png"))); // NOI18N
        botonOscurecer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonOscurecer.setDisabledIcon(null);
        botonOscurecer.setMaximumSize(new java.awt.Dimension(50, 35));
        botonOscurecer.setMinimumSize(new java.awt.Dimension(50, 35));
        botonOscurecer.setPreferredSize(new java.awt.Dimension(50, 35));
        botonOscurecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOscurecerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        contenedorContraste.add(botonOscurecer, gridBagConstraints);

        panelImagen.add(contenedorContraste);

        contenedorRotacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Rotación"));
        contenedorRotacion.setToolTipText("");
        contenedorRotacion.setMaximumSize(new java.awt.Dimension(450, 90));
        contenedorRotacion.setMinimumSize(new java.awt.Dimension(175, 91));
        contenedorRotacion.setPreferredSize(new java.awt.Dimension(450, 97));
        contenedorRotacion.setLayout(new java.awt.GridBagLayout());

        sliderRotacion.setMajorTickSpacing(180);
        sliderRotacion.setMaximum(360);
        sliderRotacion.setMinorTickSpacing(90);
        sliderRotacion.setPaintLabels(true);
        sliderRotacion.setPaintTicks(true);
        sliderRotacion.setToolTipText("");
        sliderRotacion.setValue(0);
        sliderRotacion.setMaximumSize(new java.awt.Dimension(250, 65));
        sliderRotacion.setMinimumSize(new java.awt.Dimension(250, 65));
        sliderRotacion.setPreferredSize(new java.awt.Dimension(250, 65));
        sliderRotacion.setValueIsAdjusting(true);
        sliderRotacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRotacionStateChanged(evt);
            }
        });
        sliderRotacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sliderRotacionFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorRotacion.add(sliderRotacion, gridBagConstraints);

        botonRotacion90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rotacion90.png"))); // NOI18N
        botonRotacion90.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonRotacion90.setMaximumSize(new java.awt.Dimension(50, 35));
        botonRotacion90.setMinimumSize(new java.awt.Dimension(50, 35));
        botonRotacion90.setPreferredSize(new java.awt.Dimension(50, 35));
        botonRotacion90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRotacion90ActionPerformed(evt);
            }
        });
        contenedorRotacion.add(botonRotacion90, new java.awt.GridBagConstraints());

        botonRotacion180.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rotacion180.png"))); // NOI18N
        botonRotacion180.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonRotacion180.setMaximumSize(new java.awt.Dimension(50, 35));
        botonRotacion180.setMinimumSize(new java.awt.Dimension(50, 35));
        botonRotacion180.setPreferredSize(new java.awt.Dimension(50, 35));
        botonRotacion180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRotacion180ActionPerformed(evt);
            }
        });
        contenedorRotacion.add(botonRotacion180, new java.awt.GridBagConstraints());

        botonRotacion270.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rotacion270.png"))); // NOI18N
        botonRotacion270.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonRotacion270.setMaximumSize(new java.awt.Dimension(50, 35));
        botonRotacion270.setMinimumSize(new java.awt.Dimension(50, 35));
        botonRotacion270.setPreferredSize(new java.awt.Dimension(50, 35));
        botonRotacion270.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRotacion270ActionPerformed(evt);
            }
        });
        contenedorRotacion.add(botonRotacion270, new java.awt.GridBagConstraints());

        panelImagen.add(contenedorRotacion);

        contenedorEscala.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraste"));
        contenedorEscala.setToolTipText("");
        contenedorEscala.setMaximumSize(new java.awt.Dimension(200, 90));
        contenedorEscala.setLayout(new java.awt.GridBagLayout());

        botonAumentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aumentar.png"))); // NOI18N
        botonAumentar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonAumentar.setMaximumSize(new java.awt.Dimension(50, 35));
        botonAumentar.setMinimumSize(new java.awt.Dimension(50, 35));
        botonAumentar.setPreferredSize(new java.awt.Dimension(50, 35));
        botonAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAumentarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        contenedorEscala.add(botonAumentar, gridBagConstraints);

        botonDisminuir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disminuir.png"))); // NOI18N
        botonDisminuir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonDisminuir.setMaximumSize(new java.awt.Dimension(50, 35));
        botonDisminuir.setMinimumSize(new java.awt.Dimension(50, 35));
        botonDisminuir.setPreferredSize(new java.awt.Dimension(50, 35));
        botonDisminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDisminuirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        contenedorEscala.add(botonDisminuir, gridBagConstraints);

        panelImagen.add(contenedorEscala);

        paneles.add(panelImagen);

        panelColor.setMaximumSize(new java.awt.Dimension(831, 100));
        panelColor.setNextFocusableComponent(botonPaletaColor);
        panelColor.setPreferredSize(new java.awt.Dimension(831, 100));
        panelColor.setLayout(new javax.swing.BoxLayout(panelColor, javax.swing.BoxLayout.LINE_AXIS));

        contenedorColores.setMaximumSize(new java.awt.Dimension(125, 90));
        contenedorColores.setMinimumSize(new java.awt.Dimension(125, 90));
        contenedorColores.setPreferredSize(new java.awt.Dimension(125, 90));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        contenedorColores.setLayout(flowLayout1);

        panelColores.setBorder(javax.swing.BorderFactory.createTitledBorder("Color"));
        panelColores.setMaximumSize(new java.awt.Dimension(89, 90));
        panelColores.setMinimumSize(new java.awt.Dimension(89, 90));
        panelColores.setPreferredSize(new java.awt.Dimension(125, 90));
        panelColores.setLayout(new java.awt.GridBagLayout());

        botonColorRojo.setBackground(new java.awt.Color(255, 0, 0));
        botonColorRojo.setBorder(null);
        GrupoColores.add(botonColorRojo);
        botonColorRojo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonColorRojo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonColorRojo.setMaximumSize(new java.awt.Dimension(15, 15));
        botonColorRojo.setMinimumSize(new java.awt.Dimension(15, 15));
        botonColorRojo.setPreferredSize(new java.awt.Dimension(15, 15));
        botonColorRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonColorRojoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        panelColores.add(botonColorRojo, gridBagConstraints);

        botonColorNegro.setBackground(new java.awt.Color(0, 0, 0));
        botonColorNegro.setBorder(null);
        GrupoColores.add(botonColorNegro);
        botonColorNegro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonColorNegro.setMaximumSize(new java.awt.Dimension(15, 15));
        botonColorNegro.setMinimumSize(new java.awt.Dimension(15, 15));
        botonColorNegro.setPreferredSize(new java.awt.Dimension(15, 15));
        botonColorNegro.setSelected(true);
        botonColorNegro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonColorNegroMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panelColores.add(botonColorNegro, gridBagConstraints);

        botonColorAzul.setBackground(new java.awt.Color(0, 0, 255));
        botonColorAzul.setBorder(null);
        GrupoColores.add(botonColorAzul);
        botonColorAzul.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonColorAzul.setMaximumSize(new java.awt.Dimension(15, 15));
        botonColorAzul.setMinimumSize(new java.awt.Dimension(15, 15));
        botonColorAzul.setPreferredSize(new java.awt.Dimension(15, 15));
        botonColorAzul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonColorAzulMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 15);
        panelColores.add(botonColorAzul, gridBagConstraints);

        botonColorBlanco.setBackground(new java.awt.Color(255, 255, 255));
        botonColorBlanco.setBorder(null);
        GrupoColores.add(botonColorBlanco);
        botonColorBlanco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonColorBlanco.setMaximumSize(new java.awt.Dimension(15, 15));
        botonColorBlanco.setMinimumSize(new java.awt.Dimension(15, 15));
        botonColorBlanco.setPreferredSize(new java.awt.Dimension(15, 15));
        botonColorBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonColorBlancoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 15, 0);
        panelColores.add(botonColorBlanco, gridBagConstraints);

        botonColorVerde.setBackground(new java.awt.Color(0, 255, 0));
        botonColorVerde.setBorder(null);
        GrupoColores.add(botonColorVerde);
        botonColorVerde.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonColorVerde.setMaximumSize(new java.awt.Dimension(15, 15));
        botonColorVerde.setMinimumSize(new java.awt.Dimension(15, 15));
        botonColorVerde.setPreferredSize(new java.awt.Dimension(15, 15));
        botonColorVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonColorVerdeMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 15);
        panelColores.add(botonColorVerde, gridBagConstraints);

        botonColorAmarillo.setBackground(new java.awt.Color(255, 255, 0));
        botonColorAmarillo.setBorder(null);
        GrupoColores.add(botonColorAmarillo);
        botonColorAmarillo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonColorAmarillo.setMaximumSize(new java.awt.Dimension(15, 15));
        botonColorAmarillo.setMinimumSize(new java.awt.Dimension(15, 15));
        botonColorAmarillo.setPreferredSize(new java.awt.Dimension(15, 15));
        botonColorAmarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonColorAmarilloMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 0);
        panelColores.add(botonColorAmarillo, gridBagConstraints);

        contenedorColores.add(panelColores);

        panelColor.add(contenedorColores);

        contenedorGrosor.setBorder(javax.swing.BorderFactory.createTitledBorder("Grosor"));
        contenedorGrosor.setMaximumSize(new java.awt.Dimension(90, 90));
        contenedorGrosor.setMinimumSize(new java.awt.Dimension(90, 90));
        contenedorGrosor.setPreferredSize(new java.awt.Dimension(90, 90));
        contenedorGrosor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        panelGrosor.setMaximumSize(new java.awt.Dimension(70, 50));
        panelGrosor.setMinimumSize(new java.awt.Dimension(60, 50));
        panelGrosor.setPreferredSize(new java.awt.Dimension(60, 50));

        grosor.setMaximumSize(new java.awt.Dimension(50, 28));
        grosor.setMinimumSize(new java.awt.Dimension(50, 28));
        grosor.setPreferredSize(new java.awt.Dimension(50, 28));
        grosor.setValue(1);
        grosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                grosorStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelGrosorLayout = new javax.swing.GroupLayout(panelGrosor);
        panelGrosor.setLayout(panelGrosorLayout);
        panelGrosorLayout.setHorizontalGroup(
            panelGrosorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(panelGrosorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGrosorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(grosor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelGrosorLayout.setVerticalGroup(
            panelGrosorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(panelGrosorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGrosorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(grosor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        contenedorGrosor.add(panelGrosor);

        panelColor.add(contenedorGrosor);

        contenedorEditarRelleno.setBorder(javax.swing.BorderFactory.createTitledBorder(" "));
        contenedorEditarRelleno.setMaximumSize(new java.awt.Dimension(100, 90));
        contenedorEditarRelleno.setMinimumSize(new java.awt.Dimension(95, 90));
        contenedorEditarRelleno.setPreferredSize(new java.awt.Dimension(95, 90));
        contenedorEditarRelleno.setLayout(new java.awt.GridLayout(0, 1));

        panelRelleno.setBorder(null);
        panelRelleno.setToolTipText("");
        panelRelleno.setMaximumSize(new java.awt.Dimension(90, 80));
        panelRelleno.setMinimumSize(new java.awt.Dimension(90, 80));
        panelRelleno.setPreferredSize(new java.awt.Dimension(90, 80));
        panelRelleno.setLayout(new java.awt.GridLayout(2, 1));

        checkboxRelleno.setText("Relleno");
        checkboxRelleno.setActionCommand("");
        checkboxRelleno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        checkboxRelleno.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkboxRellenoStateChanged(evt);
            }
        });
        checkboxRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxRellenoActionPerformed(evt);
            }
        });
        panelRelleno.add(checkboxRelleno);

        checkboxEditar.setText("Editar");
        checkboxEditar.setActionCommand("");
        checkboxEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        checkboxEditar.setMaximumSize(new java.awt.Dimension(69, 10));
        checkboxEditar.setMinimumSize(new java.awt.Dimension(69, 10));
        checkboxEditar.setPreferredSize(new java.awt.Dimension(69, 10));
        checkboxEditar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkboxEditarStateChanged(evt);
            }
        });
        panelRelleno.add(checkboxEditar);

        contenedorEditarRelleno.add(panelRelleno);

        panelColor.add(contenedorEditarRelleno);

        paneles.add(panelColor);

        pie.add(paneles, java.awt.BorderLayout.LINE_START);

        panelLabelFigura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelLabelFigura.setLayout(new javax.swing.BoxLayout(panelLabelFigura, javax.swing.BoxLayout.LINE_AXIS));

        labelFigura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelFigura.setText("labelFigura");
        panelLabelFigura.add(labelFigura);

        pie.add(panelLabelFigura, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pie, java.awt.BorderLayout.PAGE_END);

        archivo.setText("Archivo");

        nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/NuevoBoceto.GIF"))); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        archivo.add(nuevo);

        abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        archivo.add(abrir);

        guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Guardar.gif"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        archivo.add(guardar);

        menu.add(archivo);

        edicion.setText("Edición");

        verBarraEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        verBarraEstado.setSelected(true);
        verBarraEstado.setText("Ver barra estado");
        verBarraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBarraEstadoActionPerformed(evt);
            }
        });
        edicion.add(verBarraEstado);

        menu.add(edicion);

        imagen.setText("Imagen");

        menuRescaleOp.setText("RescaleOp");
        menuRescaleOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRescaleOpActionPerformed(evt);
            }
        });
        imagen.add(menuRescaleOp);

        menuConvolveOp.setText("ConvolveOp");
        menuConvolveOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConvolveOpActionPerformed(evt);
            }
        });
        imagen.add(menuConvolveOp);

        umbralizacion.setText("Umbralización");
        umbralizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umbralizacionActionPerformed(evt);
            }
        });
        imagen.add(umbralizacion);

        restar.setText("Restar");
        restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarActionPerformed(evt);
            }
        });
        imagen.add(restar);

        multiplicar.setText("Multiplicación");
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });
        imagen.add(multiplicar);

        sobelMenu.setText("Sobel");
        sobelMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobelMenuActionPerformed(evt);
            }
        });
        imagen.add(sobelMenu);

        menu.add(imagen);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLineaMouseClicked
        labelFigura.setText("Línea");
        botonLinea.setSelected(true);
        Lienzo.setForma(Lienzo.LINEA);
    }//GEN-LAST:event_botonLineaMouseClicked

    private void botonRectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRectanguloMouseClicked
        labelFigura.setText("Rectángulo");
        botonRectangulo.setSelected(true);
        Lienzo.setForma(Lienzo.RECTANGULO);
    }//GEN-LAST:event_botonRectanguloMouseClicked

    private void botonOvaloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOvaloMouseClicked
        labelFigura.setText("Ovalo");
        botonOvalo.setSelected(true);
        Lienzo.setForma(Lienzo.ELIPSE);
    }//GEN-LAST:event_botonOvaloMouseClicked

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed

        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.getLienzo().setColor(getVentanaInterna().getLienzo().getColor());
        vi.getLienzo().setStroke(getVentanaInterna().getLienzo().getStroke());
        vi.getLienzo().setEditar(getVentanaInterna().getLienzo().isEditar());
        vi.getLienzo().setRelleno(getVentanaInterna().getLienzo().isRelleno());
        vi.setTitle("Lienzo " + ++numVentanas);
        vi.setVisible(true);
        setVentanaInterna(vi);

    }//GEN-LAST:event_nuevoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            try {
                File f = dlg.getSelectedFile();
                VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
                BufferedImage img = vi.getLienzo().getImageOriginal();
                img = vi.getLienzo().volcado(img);

                ImageIO.write(img, "jpg", f);
                //Código 
            } catch (IOException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void botonColorNegroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonColorNegroMouseClicked
        VentanaInterna vInt = (VentanaInterna) escritorio.getSelectedFrame();
        if (vInt != null) {
            vInt.getLienzo().setColor(Color.black);
        }
    }//GEN-LAST:event_botonColorNegroMouseClicked

    private void botonColorRojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonColorRojoMouseClicked
        VentanaInterna vInt = (VentanaInterna) escritorio.getSelectedFrame();
        if (vInt != null) {
            vInt.getLienzo().setColor(Color.red);
        }
    }//GEN-LAST:event_botonColorRojoMouseClicked

    private void botonColorAzulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonColorAzulMouseClicked
        VentanaInterna vInt = (VentanaInterna) escritorio.getSelectedFrame();
        if (vInt != null) {
            vInt.getLienzo().setColor(Color.blue);
        }
    }//GEN-LAST:event_botonColorAzulMouseClicked

    private void botonColorBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonColorBlancoMouseClicked
        VentanaInterna vInt = (VentanaInterna) escritorio.getSelectedFrame();
        if (vInt != null) {
            vInt.getLienzo().setColor(Color.white);
        }
    }//GEN-LAST:event_botonColorBlancoMouseClicked

    private void botonColorAmarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonColorAmarilloMouseClicked
        VentanaInterna vInt = (VentanaInterna) escritorio.getSelectedFrame();
        if (vInt != null) {
            vInt.getLienzo().setColor(Color.yellow);
        }
    }//GEN-LAST:event_botonColorAmarilloMouseClicked

    private void botonColorVerdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonColorVerdeMouseClicked
        VentanaInterna vInt = (VentanaInterna) escritorio.getSelectedFrame();
        if (vInt != null) {
            vInt.getLienzo().setColor(Color.green);
        }
    }//GEN-LAST:event_botonColorVerdeMouseClicked

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            try {
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo().setImageOriginal(img);
                //vi.getLienzo().setImageActual(img);
                this.escritorio.add(vi);
                vi.setVisible(true);
            } catch (Exception ex) {
                System.err.println("Error al leer la imagen");
            }
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void verBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBarraEstadoActionPerformed
        if (!verBarraEstado.isSelected()) {
            panelLabelFigura.setVisible(false);
        } else {
            panelLabelFigura.setVisible(true);
        }
    }//GEN-LAST:event_verBarraEstadoActionPerformed

    private void botonLapizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLapizMouseClicked
        labelFigura.setText("Lápiz");
        botonLapiz.setSelected(true);
        Lienzo.setForma(Lienzo.PUNTO);
    }//GEN-LAST:event_botonLapizMouseClicked

    private void checkboxRellenoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkboxRellenoStateChanged
        VentanaInterna vInt = (VentanaInterna) escritorio.getSelectedFrame();
        if (vInt != null) {
            vInt.getLienzo().setRelleno(checkboxRelleno.isSelected());
        }
    }//GEN-LAST:event_checkboxRellenoStateChanged

    private void checkboxEditarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkboxEditarStateChanged
        VentanaInterna vInt = (VentanaInterna) escritorio.getSelectedFrame();
        if (vInt != null) {
            vInt.getLienzo().setEditar(checkboxEditar.isSelected());
        }
    }//GEN-LAST:event_checkboxEditarStateChanged

    private void grosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_grosorStateChanged
        VentanaInterna vInt = (VentanaInterna) escritorio.getSelectedFrame();
        if (vInt != null) {
            vInt.getLienzo().setStroke(new BasicStroke(((Integer) grosor.getValue()).floatValue()));
        }
    }//GEN-LAST:event_grosorStateChanged

    private void checkboxRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxRellenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxRellenoActionPerformed

    private void menuRescaleOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRescaleOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage imgSource = vi.getLienzo().getImageOriginal();
            if (imgSource != null) {
                try {
                    RescaleOp rop = new RescaleOp(1.0F, 100.0F, null);
                    BufferedImage imgdest = rop.filter(convertImageType(imgSource, BufferedImage.TYPE_INT_RGB), null);
                    vi.getLienzo().setImageOriginal(imgdest);
                    vi.getLienzo().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_menuRescaleOpActionPerformed

    BufferedImage convertImageType(BufferedImage img, int type) {
        if (img == null) {
            return null;
        }
        BufferedImage imgOut = new BufferedImage(img.getWidth(),
                img.getHeight(), type);
        Graphics2D g2d = imgOut.createGraphics();
        g2d.drawImage(img, 0, 0, null);
        return imgOut;
    }


    private void menuConvolveOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConvolveOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage imgSource = vi.getLienzo().getImageOriginal();
            if (imgSource != null) {
                try {
                    ConvolveOp cop = new ConvolveOp(KernelProducer.createKernel(KernelProducer.TYPE_MEDIA_3x3));
                    BufferedImage imgdest = cop.filter(imgSource, null);
                    vi.getLienzo().setImageOriginal(imgdest);
                    vi.getLienzo().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_menuConvolveOpActionPerformed

    private void botonPaletaColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPaletaColorActionPerformed
        panelColor.setVisible(true);
        panelImagen.setVisible(false);
        this.repaint();
    }//GEN-LAST:event_botonPaletaColorActionPerformed

    private void botonPaletaImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPaletaImagenActionPerformed
        panelColor.setVisible(false);
        panelImagen.setVisible(true);
        this.repaint();    }//GEN-LAST:event_botonPaletaImagenActionPerformed

    private void sliderBrilloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderBrilloStateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            if (vi.getLienzo().getImageOriginal() != null) {
                try {
                    RescaleOp rop = new RescaleOp(1.0F, (float) sliderBrillo.getValue(), null);
                    BufferedImage imgdest = rop.filter(convertImageType(vi.getLienzo().getImageOriginal(), BufferedImage.TYPE_INT_RGB), null);
                    vi.getLienzo().setImageActual(imgdest);
                    vi.getLienzo().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_sliderBrilloStateChanged

    private void sliderBrilloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sliderBrilloFocusLost
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            vi.getLienzo().setImageOriginal(vi.getLienzo().getImageActual());
        }
        sliderBrillo.setValue(0);
    }//GEN-LAST:event_sliderBrilloFocusLost

    private void listaEfectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaEfectosActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());

        switch (listaEfectos.getSelectedIndex()) {

            case KernelProducer.TYPE_MEDIA_3x3:
                if (vi != null) {
                    BufferedImage imgSource = vi.getLienzo().getImageOriginal();
                    if (imgSource != null) {
                        try {
                            ConvolveOp cop = new ConvolveOp(KernelProducer.createKernel(KernelProducer.TYPE_MEDIA_3x3));
                            BufferedImage imgdest = cop.filter(imgSource, null);
                            vi.getLienzo().setImageActual(imgdest);
                            vi.getLienzo().repaint();
                        } catch (IllegalArgumentException e) {
                            System.err.println(e.getLocalizedMessage());
                        }
                    }
                }
                break;

            case KernelProducer.TYPE_BINOMIAL_3x3:
                if (vi != null) {
                    BufferedImage imgSource = vi.getLienzo().getImageOriginal();
                    if (imgSource != null) {
                        try {
                            ConvolveOp cop = new ConvolveOp(KernelProducer.createKernel(KernelProducer.TYPE_BINOMIAL_3x3));
                            BufferedImage imgdest = cop.filter(imgSource, null);
                            vi.getLienzo().setImageActual(imgdest);
                            vi.getLienzo().repaint();
                        } catch (IllegalArgumentException e) {
                            System.err.println(e.getLocalizedMessage());
                        }
                    }
                }
                break;

            case KernelProducer.TYPE_ENFOQUE_3x3:
                if (vi != null) {
                    BufferedImage imgSource = vi.getLienzo().getImageOriginal();
                    if (imgSource != null) {
                        try {
                            ConvolveOp cop = new ConvolveOp(KernelProducer.createKernel(KernelProducer.TYPE_ENFOQUE_3x3));
                            BufferedImage imgdest = cop.filter(imgSource, null);
                            vi.getLienzo().setImageActual(imgdest);
                            vi.getLienzo().repaint();
                        } catch (IllegalArgumentException e) {
                            System.err.println(e.getLocalizedMessage());
                        }
                    }
                }

                break;

            case KernelProducer.TYPE_RELIEVE_3x3:
                if (vi != null) {
                    BufferedImage imgSource = vi.getLienzo().getImageOriginal();
                    if (imgSource != null) {
                        try {
                            ConvolveOp cop = new ConvolveOp(KernelProducer.createKernel(KernelProducer.TYPE_RELIEVE_3x3));
                            BufferedImage imgdest = cop.filter(imgSource, null);
                            vi.getLienzo().setImageActual(imgdest);
                            vi.getLienzo().repaint();
                        } catch (IllegalArgumentException e) {
                            System.err.println(e.getLocalizedMessage());
                        }
                    }
                }
                break;

            case KernelProducer.TYPE_LAPLACIANA_3x3:
                if (vi != null) {
                    BufferedImage imgSource = vi.getLienzo().getImageOriginal();
                    if (imgSource != null) {
                        try {
                            ConvolveOp cop = new ConvolveOp(KernelProducer.createKernel(KernelProducer.TYPE_LAPLACIANA_3x3));
                            BufferedImage imgdest = cop.filter(imgSource, null);
                            vi.getLienzo().setImageActual(imgdest);
                            vi.getLienzo().repaint();
                        } catch (IllegalArgumentException e) {
                            System.err.println(e.getLocalizedMessage());
                        }
                    }
                }
                break;

        }
    }//GEN-LAST:event_listaEfectosActionPerformed

    private void botonContrasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContrasteActionPerformed

        try {
            VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
            if (vi != null) {
                BufferedImage imgActual = convertImageType(vi.getLienzo().getImageActual(), BufferedImage.TYPE_INT_RGB);
                LookupTable ltp = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_SFUNCION);
                LookupOp lop = new LookupOp(ltp, null);
                BufferedImage imgdest = lop.filter(imgActual, null);

                if (imgdest != null) {
                    vi.getLienzo().setImageOriginal(imgdest);
                    vi.getLienzo().repaint();
                }
            }
        } catch (Exception e) {
            System.err.println("Error en el contraste");
        }
    }//GEN-LAST:event_botonContrasteActionPerformed

    private void botonIluminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIluminarActionPerformed
        try {
            VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
            if (vi != null) {
                BufferedImage imgActual = convertImageType(vi.getLienzo().getImageActual(), BufferedImage.TYPE_INT_RGB);
                LookupTable ltp = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_LOGARITHM);
                LookupOp lop = new LookupOp(ltp, null);
                BufferedImage imgdest = lop.filter(imgActual, null);

                if (imgdest != null) {
                    vi.getLienzo().setImageOriginal(imgdest);
                    vi.getLienzo().repaint();
                }
            }
        } catch (Exception e) {
            System.err.println("Error al iluminar");
        }
    }//GEN-LAST:event_botonIluminarActionPerformed

    private void botonOscurecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOscurecerActionPerformed
        try {
            VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
            if (vi != null) {
                BufferedImage imgActual = convertImageType(vi.getLienzo().getImageActual(), BufferedImage.TYPE_INT_RGB);
                LookupTable ltp = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_POWER);
                LookupOp lop = new LookupOp(ltp, null);
                BufferedImage imgdest = lop.filter(imgActual, null);
                if (imgdest != null) {
                    vi.getLienzo().setImageOriginal(imgdest);
                    vi.getLienzo().repaint();
                }
            }
        } catch (Exception e) {
            System.err.println("Error al oscurecer");
        }
    }//GEN-LAST:event_botonOscurecerActionPerformed

    private void sliderRotacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRotacionStateChanged
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage imgSource = vi.getLienzo().getImageOriginal();
            double r = Math.toRadians(sliderRotacion.getValue());
            Point p = new Point(imgSource.getWidth() / 2, imgSource.getHeight() / 2);
            AffineTransform at = AffineTransform.getRotateInstance(r, p.x, p.y);
            AffineTransformOp atop;
            atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
            BufferedImage imgdest = atop.filter(imgSource, null);
            if (imgdest != null) {
                vi.getLienzo().setImageActual(imgdest);
                vi.getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_sliderRotacionStateChanged

    private void botonRotacion90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRotacion90ActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage imgSource = vi.getLienzo().getImageActual();
            double r = Math.toRadians(90);
            Point p = new Point(imgSource.getWidth() / 2, imgSource.getHeight() / 2);
            AffineTransform at = AffineTransform.getRotateInstance(r, p.x, p.y);
            AffineTransformOp atop;
            atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
            BufferedImage imgdest = atop.filter(imgSource, null);
            if (imgdest != null) {
                vi.getLienzo().setImageOriginal(imgdest);
                vi.getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_botonRotacion90ActionPerformed

    private void botonRotacion180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRotacion180ActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage imgSource = vi.getLienzo().getImageActual();
            double r = Math.toRadians(180);
            Point p = new Point(imgSource.getWidth() / 2, imgSource.getHeight() / 2);
            AffineTransform at = AffineTransform.getRotateInstance(r, p.x, p.y);
            AffineTransformOp atop;
            atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
            BufferedImage imgdest = atop.filter(imgSource, null);
            if (imgdest != null) {
                vi.getLienzo().setImageOriginal(imgdest);
                vi.getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_botonRotacion180ActionPerformed

    private void botonRotacion270ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRotacion270ActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage imgSource = vi.getLienzo().getImageActual();
            double r = Math.toRadians(270);
            Point p = new Point(imgSource.getWidth() / 2, imgSource.getHeight() / 2);
            AffineTransform at = AffineTransform.getRotateInstance(r, p.x, p.y);
            AffineTransformOp atop;
            atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
            BufferedImage imgdest = atop.filter(imgSource, null);
            if (imgdest != null) {
                vi.getLienzo().setImageOriginal(imgdest);
                vi.getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_botonRotacion270ActionPerformed

    private void botonAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAumentarActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage imgSource = vi.getLienzo().getImageActual();
            AffineTransform at = AffineTransform.getScaleInstance(1.25, 1.25);
            AffineTransformOp atop;
            atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
            BufferedImage imgdest = atop.filter(imgSource, null);
            if (imgdest != null) {
                vi.getLienzo().setImageOriginal(imgdest);
                vi.getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_botonAumentarActionPerformed

    private void botonDisminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDisminuirActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage imgSource = vi.getLienzo().getImageActual();
            AffineTransform at = AffineTransform.getScaleInstance(0.75, 0.75);
            AffineTransformOp atop;
            atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
            BufferedImage imgdest = atop.filter(imgSource, null);
            if (imgdest != null) {
                vi.getLienzo().setImageOriginal(imgdest);
                vi.getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_botonDisminuirActionPerformed

    private void sliderRotacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sliderRotacionFocusLost
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            vi.getLienzo().setImageOriginal(vi.getLienzo().getImageActual());
        }
        sliderRotacion.setValue(0);
    }//GEN-LAST:event_sliderRotacionFocusLost

    private void umbralizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umbralizacionActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage imgSource = vi.getLienzo().getImageActual();    
            UmbralizacionOp umbralizacion = new UmbralizacionOp(120);
            BufferedImage imgdest = umbralizacion.filter(imgSource, null);
            
            if(imgdest !=null){
                vi.getLienzo().setImageActual(imgdest);
                vi.getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_umbralizacionActionPerformed

    private void restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage imgRight = vi.getLienzo().getImageActual();
            VentanaInterna viNext = (VentanaInterna) escritorio.selectFrame(true);
            if (viNext != null) {
                BufferedImage imgLeft = viNext.getLienzo().getImageActual();
                RestaOp op = new RestaOp(imgLeft);
                BufferedImage imgdest = op.filter(imgRight, null);
                if (imgdest != null) {
                    vi.getLienzo().setImageActual(imgdest);
                    vi.getLienzo().repaint();
                }
            }
        }
    }//GEN-LAST:event_restarActionPerformed

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage imgRight = vi.getLienzo().getImageActual();
            VentanaInterna viNext = (VentanaInterna) escritorio.selectFrame(true);
            if (viNext != null) {
                BufferedImage imgLeft = viNext.getLienzo().getImageActual();
                MultiplicacionOp op = new MultiplicacionOp(imgLeft);
                BufferedImage imgdest = op.filter(imgRight, null);
                if (imgdest != null) {
                    vi.getLienzo().setImageActual(imgdest);
                    vi.getLienzo().repaint();
                }
            }
        }
    }//GEN-LAST:event_multiplicarActionPerformed

    private void sobelMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobelMenuActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage imgSource = vi.getLienzo().getImageActual();    
            SobelOp sobel = new SobelOp();
            BufferedImage imgdest = sobel.filter(imgSource, null);
            
            if(imgdest !=null){
                vi.getLienzo().setImageActual(imgdest);
                vi.getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_sobelMenuActionPerformed

    public VentanaInterna getVentanaInterna() {
        return vi;
    }

    public void setVentanaInterna(VentanaInterna vi) {
        this.vi = vi;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar BotonesFiguras;
    private javax.swing.ButtonGroup BotonesMenu;
    private javax.swing.ButtonGroup GrupoColores;
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenu archivo;
    private javax.swing.JButton botonAumentar;
    private javax.swing.JButton botonColorAmarillo;
    private javax.swing.JButton botonColorAzul;
    private javax.swing.JButton botonColorBlanco;
    private javax.swing.JButton botonColorNegro;
    private javax.swing.JButton botonColorRojo;
    private javax.swing.JButton botonColorVerde;
    private javax.swing.JButton botonContraste;
    private javax.swing.JButton botonDisminuir;
    private javax.swing.JButton botonIluminar;
    private javax.swing.JToggleButton botonLapiz;
    private javax.swing.JToggleButton botonLinea;
    private javax.swing.JButton botonOscurecer;
    private javax.swing.JToggleButton botonOvalo;
    private javax.swing.JRadioButton botonPaletaColor;
    private javax.swing.JRadioButton botonPaletaImagen;
    private javax.swing.JToggleButton botonRectangulo;
    private javax.swing.JButton botonRotacion180;
    private javax.swing.JButton botonRotacion270;
    private javax.swing.JButton botonRotacion90;
    private javax.swing.JPanel botonesPaletas;
    private javax.swing.JCheckBox checkboxEditar;
    private javax.swing.JCheckBox checkboxRelleno;
    private javax.swing.JPanel contenedorBrillo;
    private javax.swing.JPanel contenedorColores;
    private javax.swing.JPanel contenedorContraste;
    private javax.swing.JPanel contenedorEditarRelleno;
    private javax.swing.JPanel contenedorEfecto;
    private javax.swing.JPanel contenedorEscala;
    private javax.swing.JPanel contenedorGrosor;
    private javax.swing.JPanel contenedorRotacion;
    private javax.swing.JPanel cuerpo;
    private javax.swing.JMenu edicion;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JSpinner grosor;
    private javax.swing.ButtonGroup grupoPaletas;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenu imagen;
    private javax.swing.JLabel labelFigura;
    private javax.swing.JComboBox listaEfectos;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuConvolveOp;
    private javax.swing.JMenuItem menuRescaleOp;
    private javax.swing.JMenuItem multiplicar;
    private javax.swing.JMenuItem nuevo;
    private javax.swing.JPanel paletaOpciones;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelColores;
    private javax.swing.JPanel panelGrosor;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel panelLabelFigura;
    private javax.swing.JPanel panelRelleno;
    private javax.swing.JPanel paneles;
    private javax.swing.JPanel pie;
    private javax.swing.JMenuItem restar;
    private javax.swing.JSlider sliderBrillo;
    private javax.swing.JSlider sliderRotacion;
    private javax.swing.JMenuItem sobelMenu;
    private javax.swing.JMenuItem umbralizacion;
    private javax.swing.JCheckBoxMenuItem verBarraEstado;
    // End of variables declaration//GEN-END:variables
}
