/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal.VentanasInternas;

import java.awt.image.BufferedImage;
import java.util.Vector;
import practicaFinal.Lienzo;
import practicaFinal.VentanaPrincipal;
import practicaFinal.shapes.IOShape;

/**
 *
 * @author oskyar
 */
public class VentanaInternaImagen extends javax.swing.JInternalFrame {

    public static void showImage(BufferedImage img) {
        showImage(img, "Imagen");
    }

    public static void showImage(BufferedImage img, String title) {
        VentanaInternaImagen vi = new VentanaInternaImagen();
        if (img != null) {
            vi.getLienzo().setImageOriginal(img);
            VentanaPrincipal.getEscritorio().add(vi);
            vi.setVisible(true);

            double width, height;
            if (VentanaPrincipal.getEscritorio().getWidth() < img.getWidth()) {
                width = VentanaPrincipal.getEscritorio().getWidth();
            } else {
                width = img.getWidth();
            }
            if (VentanaPrincipal.getEscritorio().getHeight() < img.getHeight()) {
                height = VentanaPrincipal.getEscritorio().getHeight();
            } else {
                height = img.getHeight();
            }

            vi.setSize((int) width, (int) height);
        }
        vi.setTitle(title);

    }

    /**
     * Creates new form VentanaInterna
     */
    public VentanaInternaImagen() {
        initComponents();
    }

    public Lienzo getLienzo() {
        return lienzo2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2 = new practicaFinal.Lienzo();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout lienzo2Layout = new javax.swing.GroupLayout(lienzo2);
        lienzo2.setLayout(lienzo2Layout);
        lienzo2Layout.setHorizontalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        lienzo2Layout.setVerticalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        VentanaPrincipal.getInstance().showToolsBarsOrNot(VentanaPrincipal.SHOW_TOOLBAR_IMAGE);
        BufferedImage imgDest = lienzo2.getImageOriginal();
        if (imgDest != null) {
            if (imgDest.getType() == BufferedImage.TYPE_BYTE_GRAY) {
                VentanaPrincipal.getInstance().activateFilterColorImage(false);
            } else {
                VentanaPrincipal.getInstance().activateFilterColorImage(true);
            }
        }
        
        VentanaInternaImagen vi = (VentanaInternaImagen) this;
        if (vi != null) {
            Vector<String> listData = new Vector();
            int i = 0;
            for (IOShape s : vi.getLienzo().getvShape()) {
                listData.add(s.getName() + " " + ++i);
            }
            VentanaPrincipal.getInstance().getFigureList().setListData(listData);
            if (!vi.getLienzo().getvShapeSelected().isEmpty()) {
                int selectedIndices[] = new int[vi.getLienzo().getvShapeSelected().size()];
                i = 0;
                for (Integer index : vi.getLienzo().getvShapeSelected()) {
                    selectedIndices[i++] = index;
                }
                VentanaPrincipal.getInstance().getFigureList().setSelectedIndices(selectedIndices);
            }
        }

    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        VentanaInternaImagen vi = (VentanaInternaImagen) this;
        if(vi!=null){
            VentanaPrincipal.getInstance().getFigureList().setListData(new Vector());
            VentanaPrincipal.getInstance().repaint();
        }
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private practicaFinal.Lienzo lienzo2;
    // End of variables declaration//GEN-END:variables
}
